export enum SpreedlyGatewayCharacteristicEnum {
    PURCHASE = 'purchase',
    AUTHORIZE = 'authorize',
    CAPTURE = 'capture',
    CREDIT = 'credit',
    GENERAL_CREDIT = 'general_credit',
    VOID = 'void',
    ADJUST = 'adjust',
    VERIFY = 'verify',
    REFERENCE_PURCHASE = 'reference_purchase',
    PURCHASE_VIA_PRE_AUTHORIZATION = 'purchase_via_preauthorization',
    OFFSITE_PURCHASE = 'offsite_purchase',
    OFFSITE_AUTHORIZE = 'offsite_authorize',
    THIRD_SECURE_PURCHASE = '3dsecure_purchase',
    THIRD_SECURE_AUTHORIZE = '3dsecure_authorize',
    STORE = 'store',
    REMOVE = 'remove',
    REFERENCE_AUTHORIZATION = 'reference_authorization',
    THIRD_SECURE_SECOND_PURCHASE = '3dsecure_2_purchase',
    THIRD_SECURE_SECOND_AUTHORIZE = '3dsecure_2_authorize',
}
